### ISSUE TITLE
Error when running sudo python3 main.py

### ISSUE THREAD

**Issue by AGHiya23** [Siyuanw/kinesis#21]
When I run sudo python3 main.py I get an error "AttributeError: module 'ssl' has no attribute 'wrap_socket'"

What should I do.

**Comment by AGHiya23** [comment]
Does anyone have a solution?

**Comment by Montana** [comment]
Same but different errors:

```bash
sudo python3.11 main.py
Traceback (most recent call last):
  File "/Users/montana/Desktop/kinesis-main/main.py", line 9, in <module>
    import eventlet
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
```
There's probably not Arm support.

**Comment by AGHiya23** [comment]
I got it to work, I just uninstalled python 12 and removed python entirely from my device and then downloaded python 11.6 and that seemed to fix the issue.
