### ISSUE TITLE
Unsupported platform error

### ISSUE THREAD

**Issue by SuperMario22922** [Siyuanw/kinesis#29]
```
hsak@192-168-1-106 kinesis % sudo python main.py
Traceback (most recent call last):
  File "/Users/hsak/kinesis/main.py", line 9, in <module>
    import eventlet
  File "/opt/homebrew/lib/python3.11/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/opt/homebrew/lib/python3.11/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/opt/homebrew/lib/python3.11/site-packages/eventlet/green/socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "/opt/homebrew/lib/python3.11/site-packages/eventlet/support/greendns.py", line 79, in <module>
    setattr(dns, pkg, import_patched('dns.' + pkg))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/eventlet/support/greendns.py", line 61, in import_patched
    return patcher.import_patched(module_name, **modules)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/eventlet/patcher.py", line 132, in import_patched
    return inject(
           ^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/eventlet/patcher.py", line 109, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dns/asyncquery.py", line 32, in <module>
    import dns.quic
  File "/opt/homebrew/lib/python3.11/site-packages/dns/quic/__init__.py", line 35, in <module>
    import trio
  File "/opt/homebrew/lib/python3.11/site-packages/trio/__init__.py", line 19, in <module>
    from ._core import TASK_STATUS_IGNORED as TASK_STATUS_IGNORED  # isort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/trio/_core/__init__.py", line 21, in <module>
    from ._local import RunVar
  File "/opt/homebrew/lib/python3.11/site-packages/trio/_core/_local.py", line 5, in <module>
    from . import _run
  File "/opt/homebrew/lib/python3.11/site-packages/trio/_core/_run.py", line 2548, in <module>
    raise NotImplementedError("unsupported platform")
NotImplementedError: unsupported platform
```

get this error every time i try to run the app. python 3.11.6 and macOS Sonoma. how do i fix this?

**Comment by RittikaJindalTR** [comment]
i am getting the same err, were u able to fix it ?
