### ISSUE TITLE
Doesn't work after one successful try.

### ISSUE THREAD

**Issue by fjybiocs** [Siyuanw/kinesis#37]
I run it successfully once, and I can't start it again.

errors:
```
sudo python3 main.py            
Traceback (most recent call last):
  File "/Users/me/Downloads/kinesis-main 2/main.py", line 84, in <module>
    create_tunnel()
  File "/Users/me/Downloads/kinesis-main 2/main.py", line 79, in create_tunnel
    asyncio.run(start_quic_tunnel(rsd))
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/me/Downloads/kinesis-main 2/main.py", line 52, in start_quic_tunnel
    with create_core_device_tunnel_service(service_provider, autopair=True) as service:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Downloads/kinesis-main 2/.venv/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 568, in create_core_device_tunnel_service
    service.connect(autopair=autopair)
  File "/Users/me/Downloads/kinesis-main 2/.venv/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 208, in connect
    if not self._validate_pairing():
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Downloads/kinesis-main 2/.venv/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 440, in _validate_pairing
    peer_public_key = X25519PublicKey.from_public_bytes(data[PairingDataComponentType.PUBLIC_KEY])
                                                        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: EnumIntegerString.new(3, 'PUBLIC_KEY')
```

**Comment by rborkow** [comment]
Same error here on a fresh install.

Seems like an issue with the `pymobiledevice3` library, fixed in v2.32.0 : https://github.com/doronz88/pymobiledevice3/pull/713

**Comment by marcusrohden** [comment]
also happening here. just tried

**Comment by N1-TR0** [comment]
use it in a venv don't run it natively I got the same thing when trying to use it with another iPhone but it works flawlessly on my main device
