### ISSUE TITLE
issues running the script 

### ISSUE THREAD

**Issue by N1-TR0** [Siyuanw/kinesis#42]
here's the terminal output:

`sudo python3 main.py
2024-04-29 19:15:56 MacBook-Pro.local zeroconf[46155] WARNING Error with socket 59 (('fe80::aede:48ff:fe00:1122', 5353, 0, 4))): [Errno 65] No route to host
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/selector_events.py", line 1196, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 65] No route to host
Traceback (most recent call last):
  File "/path/to/kinesis-main/main.py", line 84, in <module>
    create_tunnel()
  File "/path/to/kinesis-main/main.py", line 79, in create_tunnel
    asyncio.run(start_quic_tunnel(rsd))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/path/to/kinesis-main/main.py", line 52, in start_quic_tunnel
    with create_core_device_tunnel_service(service_provider, autopair=True) as service:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 568, in create_core_device_tunnel_service
    service.connect(autopair=autopair)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 208, in connect
    if not self._validate_pairing():
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 440, in _validate_pairing
    peer_public_key = X25519PublicKey.from_public_bytes(data[PairingDataComponentType.PUBLIC_KEY])
                                                        ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: EnumIntegerString.new(3, 'PUBLIC_KEY')
`

**Comment by anattemptatsomethinggreat** [comment]
On your phone go to Settings>Developer>Clear Trusted Computers. Then redo the setup process.

**Comment by sgregory8** [comment]
Open the `requirements.txt` file and change pymobiledevice3 to version 2.30.1, worked for me at least! Link: https://github.com/Siyuanw/kinesis/issues/30#issuecomment-1855143913
