### ISSUE TITLE
Enhanced Version of Kinesis: Updates and New Features Available

### ISSUE THREAD

**Issue by pujux** [Siyuanw/kinesis#44]
Hello everyone!

I'm excited to share that since it hasn't been updated since October 2023, I've forked the repository and made several updates. 

My version includes fixes for a number of previously reported issues, and I've also added new features that many of you have requested. I believe these updates will enhance the experience and I'm eager to hear your feedback to make it even better.

You can find my forked repository here: https://github.com/pujux/magic-carpet. Please feel free to check it out, and any contributions or suggestions are highly welcomed!

Thank you for your continuous support and enthusiasm towards improving this project.

Best regards,
Julian

**Comment by pujux** [comment]
### Additional Features
- Saved Routes
- Teleport Mode
- Improved Speed (faster but still completely safe)
- Lock / Edit Mode (protects for unwanted route changes when moving around)
- Location & Coordinate Search
- Coordinate Display

**Comment by anattemptatsomethinggreat** [comment]
Cool program. How do I location search though? I'm not seeing the option and this would be a game changer. Let me know.

**Comment by pujux** [comment]
@anattemptatsomethinggreat it should be available on the top left (it's a magnifying glass icon) -> I'm currently trying to fix it as I seem to have broken it in my last update.

**Comment by andyj** [comment]
hey @pujux I am currently getting this error

```


      ============ Building the readline extension module ============

      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-14.0-arm64-cpython-312
      copying readline.py -> build/lib.macosx-14.0-arm64-cpython-312
      running egg_info
      writing gnureadline.egg-info/PKG-INFO
      writing dependency_links to gnureadline.egg-info/dependency_links.txt
      writing top-level names to gnureadline.egg-info/top_level.txt
      reading manifest file 'gnureadline.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'gnureadline.egg-info/SOURCES.txt'
      running build_ext
      building 'gnureadline' extension
      creating build/temp.macosx-14.0-arm64-cpython-312
      creating build/temp.macosx-14.0-arm64-cpython-312/Modules
      creating build/temp.macosx-14.0-arm64-cpython-312/Modules/3.x
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -DHAVE_RL_APPEND_HISTORY -DHAVE_RL_CALLBACK -DHAVE_RL_CATCH_SIGNAL -DHAVE_RL_COMPLETION_APPEND_CHARACTER -DHAVE_RL_COMPLETION_DISPLAY_MATCHES_HOOK -DHAVE_RL_COMPLETION_MATCHES -DHAVE_RL_COMPLETION_SUPPRESS_APPEND -DHAVE_RL_PRE_INPUT_HOOK -DHAVE_RL_RESIZE_TERMINAL -I. -IModules/3.x -I/Users/andyjarrett/Projects/scribble/kinesis/.venv/include -I/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c Modules/3.x/readline.c -o build/temp.macosx-14.0-arm64-cpython-312/Modules/3.x/readline.o
      Modules/3.x/readline.c:347:19: error: call to undeclared function 'append_history'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
          errno = err = append_history(
                        ^
      Modules/3.x/readline.c:1160:5: error: use of undeclared identifier 'rl_completion_suppress_append'
          rl_completion_suppress_append = 0;
          ^
      Modules/3.x/readline.c:1317:5: error: use of undeclared identifier 'rl_catch_signals'
          rl_catch_signals = 0;
          ^
      Modules/3.x/readline.c:1340:17: error: call to undeclared function 'rl_resize_terminal'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                      rl_resize_terminal();
                      ^
      Modules/3.x/readline.c:1340:17: note: did you mean 'rl_reset_terminal'?
      /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/editline/readline.h:181:8: note: 'rl_reset_terminal' declared here
      void             rl_reset_terminal(const char *);
                       ^
      4 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gnureadline
Failed to build gnureadline
ERROR: Could not build wheels for gnureadline, which is required to install pyproject.toml-based projects
```

**Comment by andyj** [comment]
Fixed my issue. Something with MacOS screwed over my Python / Homebrew versions. A long process but got Python3 and PIP3 looking at the right place and all is good.

**Comment by SystemSmart** [comment]
I keep getting:

WARNING Error with socket 4 (('fe80::aede:48ff:fe00:1122', 5353, 0, 4))): [Errno 65] No route to host
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/selector_events.py", line 1196, in sendto
    self._sock.sendto(data, addr)

**Comment by anattemptatsomethinggreat** [comment]
@SystemSmart is your phone plugged in and in developer mode?

**Comment by R2-t** [comment]
> Fixed my issue. Something with MacOS screwed over my Python / Homebrew versions. A long process but got Python3 and PIP3 looking at the right place and all is good.

I haven't been able to solve that error even though I got a new Python version

**Comment by pujux** [comment]
@andyj @Santiago-Torres14 try using exactly 3.11.8 in your virtual environment (at least thats what I am and have been using just fine)

**Comment by pujux** [comment]
> I keep getting:
> 
> WARNING Error with socket 4 (('fe80::aede:48ff:fe00:1122', 5353, 0, 4))): [Errno 65] No route to host Traceback (most recent call last): File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/selector_events.py", line 1196, in sendto self._sock.sendto(data, addr)

I have also been getting this error on another M1 macbook but could not resolve it unfortunately, I remember I tried fixing it by looking at the firewall but couldn't see what's actually wrong. Same phone works fine on my laptop, so it can't really be the phone I suppose.

---
To keep this thread clean please create an issue on https://github.com/pujux/magic-carpet for any further discussion or help 😄

**Comment by pujux** [comment]
Just merged a new feature which enables loading routes from .gpx files 🎉
