### ISSUE TITLE
No such service: com.apple.instruments.dtservicehub

### ISSUE THREAD

**Issue by Han-Zhao** [Siyuanw/kinesis#5]
Please help. Many thanks in advance!
I am able to host but location teleporting is not working. log shows:

$ sudo python3 main.py
2023-10-07 18:10:14 SimoneintheAir quic[85031] INFO [7e5ecf066737215b] ALPN negotiated protocol RemotePairingTunnelProtocol
2023-10-07 18:10:14 SimoneintheAir quic[85031] INFO [7e5ecf066737215b] Duplicate CRYPTO data received for epoch Epoch.HANDSHAKE
UDID: 00008120-0004284611A3C01E
ProductType: iPhone15,2
ProductVersion: 17.0.2
Interface: utun6
--rsd fd10:22d7:f182::1 55887
--port 3000
(85034) wsgi starting up on http://127.0.0.1:3000
(85034) accepted ('127.0.0.1', 51115)
127.0.0.1 - - [07/Oct/2023 18:10:19] "GET / HTTP/1.1" 200 3195 0.000592
127.0.0.1 - - [07/Oct/2023 18:10:19] "GET /main.css HTTP/1.1" 200 370 0.000524
127.0.0.1 - - [07/Oct/2023 18:10:19] "GET /index.js HTTP/1.1" 200 7242 0.000533
127.0.0.1 - - [07/Oct/2023 18:10:19] "GET /socket.io/?EIO=4&transport=polling&t=Oi8-GSD HTTP/1.1" 200 278 0.000415
(85034) accepted ('127.0.0.1', 51118)
(85034) accepted ('127.0.0.1', 51119)
message handler error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/engineio/server.py", line 642, in run_handler
    return self.handlers[event](*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/socketio/server.py", line 782, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/socketio/server.py", line 672, in _handle_connect
    success = self._trigger_event(
              ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/socketio/server.py", line 749, in _trigger_event
    return self.handlers[namespace][event](*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Simone/Documents/kinesis/main.py", line 28, in connect
    dvt = DvtSecureSocketProxyService(rsd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymobiledevice3/services/dvt/dvt_secure_socket_proxy.py", line 26, in __init__
    super().__init__(lockdown, service_name, remove_ssl_context=remove_ssl_context)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymobiledevice3/services/remote_server.py", line 241, in __init__
    super().__init__(lockdown, service_name, is_developer_service=is_developer_service)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymobiledevice3/services/lockdown_service.py", line 20, in __init__
    service = start_service(service_name, include_escrow_bag=include_escrow_bag)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymobiledevice3/remote/remote_service_discovery.py", line 69, in start_lockdown_developer_service
    return self.start_lockdown_service_without_checkin(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymobiledevice3/remote/remote_service_discovery.py", line 46, in start_lockdown_service_without_checkin
    return LockdownServiceConnection.create_using_tcp(self.service.address[0], self.get_service_port(name))
                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pymobiledevice3/remote/remote_service_discovery.py", line 91, in get_service_port
    raise InvalidServiceError(f'No such service: {name}')
pymobiledevice3.exceptions.InvalidServiceError: No such service: com.apple.instruments.dtservicehub

**Comment by Han-Zhao** [comment]
Resolved. Turned out I just didn't turn on Dev mode on my device.
